### ISSUE TITLE
Can I use a Rpi and CAN board instead of the micro controller?

### ISSUE THREAD

**Issue by oilcan-productions** [rubillos/RV-Bridge#1]
I have a coachproxy setup from a previous project that I abandoned a year ago. Could the software be adapted to run on an RPi 4 with a CAN board attached>

**Comment by rubillos** [comment]
That wouldn’t be easy… this project is codes using the HomeSpan library which is designed for the ESP32. I think you’d have an easier time using the coachproxy definition files for your Motorhome to define a setup file for this project.

**Comment by oilcan-productions** [comment]
Thanks I got one of the ESP32 boards now.
