### ISSUE TITLE
Add capability to configure Wi-Fi settings without rebuilding the code

### ISSUE THREAD

**Issue by oilcan-productions** [rubillos/RV-Bridge#6]
I have several Wi-Fi hotspots I use the adapter with. currently I modified a private build to scan for Wi-Fi and select the right access point  and password from a list rather than a single AP in the config file.

I think the functionality that if the configured wifi is not found the device comes up in AP mode and I can connect to a simple page to configure wifi there and write that to the NVRAM or the config file would be great.

**Comment by oilcan-productions** [comment]
I am going to take a stab at this over the next 2 weeks or so and send a PR

**Comment by rubillos** [comment]
Great! (I'd suggest just adding an #ifdef on ssid around setWifiCredentials so if ssid is not defined then you can just use the HomeSpan serial commands to set/change the wifi setup).

**Comment by mkostersitz** [comment]
Thanks for the suggestion. I submitted https://github.com/rubillos/RV-Bridge/pull/8/ with the change

**Comment by rubillos** [comment]
Added ability to not set wifi credentials by defining SKIP_WIFI_CREDENTIALS.
